### ISSUE TITLE
Concurbugrency 

### ISSUE THREAD

**Issue by riggs** [QuantumLeaps/lock-free-ring-buffer#1]
https://github.com/QuantumLeaps/lock-free-ring-buffer/blob/d9e6e69287b0578fb0c665843bde83cec58e145e/src/ring_buf.c#L71-L73

Given a RingBuf with `tail` pointing to the last element of `buf` and `head` pointing to the penultimate element, if `RingBuf_get` is called and interrupted after line 71 but before line 73, two or more calls to `RingBuf_put` from the ISR will cause data corruption because `tail` is pointing to an invalid index.

**Comment by quantum-leaps** [comment]
Yes, you are right. The head/tail indexes should only hold valid values, as opposed to occasionally holding a value one beyond the end of the buffer. The issue has been fixed and released as version 1.1.0. Please check. Thanks for pointing this out.
--MMS

**Comment by riggs** [comment]
Looks like a nice, clean fix.
