### ISSUE TITLE
Is volatile needed?

### ISSUE THREAD

**Issue by pozzugno** [QuantumLeaps/lock-free-ring-buffer#2]
I think volatile is needed to guarantee a lock-free implementation.

Suppose I use your lfrb in a UART driver for AVR8 architecture. In the rx ISR I could call RingBuf_put() to push new incoming data into the buffer. I could call RingBuf_get() from mainloop code to retrieve new data from the buffer.

Even if I define RingBufCtr=uint8_t (atomic access), I think volatile is needed to force the compiler to respect the order of instructions.

```
    if (me->head != tail) { /* ring buffer NOT empty? */
        *pel = me->buf[tail];
```

What happens if the compiler decides to read buf[tail] before testing if condition? This rearranging should be perfectly allowed without any volatile. I think you must access both head and buf as volatile in RingBuf_get(), to avoid this.

On the contrary, it should be used a volatile access for tail and buf in RingBuf_put().

What do you think?

**Comment by quantum-leaps** [comment]
The described scenario is incompatible with the C language specification, so a C compiler cannot generate code that would change the order of evaluation like that. Please google for the term "C Sequence Points".

**Comment by quantum-leaps** [comment]
I think that `volatile` is not needed. Please also see the post ["Why the volatile type class should not be used"](https://docs.kernel.org/5.19/process/volatile-considered-harmful.html). With that comment, this issue is closed.
